/* SPDX-FileCopyrightText: 2025 LichtFeld Studio Authors
 * SPDX-License-Identifier: GPL-3.0-or-later */

/**
 * @file c10/cuda/impl/cuda_cmake_macros.h
 * @brief Shim for PyTorch CUDA cmake macros - provides stub for ROCm builds.
 *
 * This file is normally generated by PyTorch's CMake build system.
 * For ROCm/HIP builds using pip-installed PyTorch, we provide this shim.
 */

#ifndef C10_CUDA_IMPL_CUDA_CMAKE_MACROS_H_
#define C10_CUDA_IMPL_CUDA_CMAKE_MACROS_H_

// For ROCm builds, CUDA is not used
#define C10_CUDA_BUILD_SHARED_LIBS

// Define that we're using HIP instead of CUDA
#ifndef USE_ROCM
#define USE_ROCM 1
#endif

#endif // C10_CUDA_IMPL_CUDA_CMAKE_MACROS_H_
